# Generated by Django 5.2.11 on 2026-03-03 04:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=300)),
                ('entry_type', models.CharField(choices=[('EVENT', 'Event'), ('ACTIVITY', 'Activity'), ('EXAM', 'Exam'), ('HOLIDAY', 'Holiday')], max_length=10)),
                ('related_entity_id', models.UUIDField(blank=True, help_text='UUID of the linked Event/Activity/Exam.', null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, help_text='NULL for entries visible to all branches.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_entries', to='core.branch')),
            ],
            options={
                'verbose_name_plural': 'calendar entries',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['start_date'], name='calendar_ap_start_d_ec7c83_idx'), models.Index(fields=['branch', 'start_date'], name='calendar_ap_branch__25c215_idx')],
            },
        ),
    ]
