# Generated by Django 5.2.11 on 2026-03-03 04:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(help_text='e.g. DIRECTOR, PRINCIPAL, HOD, SECTION_INCHARGE', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('email', models.EmailField(help_text='Login email — must be unique across the system.', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role_type', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SCHOOL_ADMIN', 'School Admin'), ('FACULTY', 'Faculty'), ('STUDENT', 'Student'), ('PARENT', 'Parent')], max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this user belongs to. NULL for super admins.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.branch')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('faculty_code', models.CharField(max_length=20)),
                ('level', models.CharField(choices=[('L1', 'Level 1 (Principal, Heads)'), ('L2', 'Level 2 (HODs, Incharges)'), ('L3', 'Level 3 (Subject Teachers)')], max_length=5)),
                ('grade', models.CharField(blank=True, default='', max_length=10)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacultyRoleMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('scope_type', models.CharField(choices=[('BRANCH', 'Branch Only'), ('GLOBAL', 'All Branches')], default='BRANCH', max_length=10)),
                ('branch', models.ForeignKey(blank=True, help_text='NULL for GLOBAL scope roles.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
                ('class_assigned', models.ForeignKey(blank=True, help_text='Class scope (e.g., Section Incharge for Class 10).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_mappings', to='academics.class')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_mappings', to='accounts.faculty')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_mappings', to='academics.section')),
                ('subject', models.ForeignKey(blank=True, help_text='Subject scope (e.g., HOD for Physics).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_mappings', to='academics.subject')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_mappings', to='accounts.role')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('permission_key', models.CharField(help_text='e.g. can_mark_attendance, can_upload_marks', max_length=100)),
                ('branch_scope_allowed', models.BooleanField(default=False, help_text='If True, this role can see cross-branch data.')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.role')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('admission_number', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, default='', max_length=200)),
                ('father_phone', models.CharField(blank=True, default='', max_length=15)),
                ('father_occupation', models.CharField(blank=True, default='', max_length=100)),
                ('mother_name', models.CharField(blank=True, default='', max_length=200)),
                ('mother_phone', models.CharField(blank=True, default='', max_length=15)),
                ('mother_occupation', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('aadhar_number', models.CharField(blank=True, default='', max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.branch')),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.class')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.house')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentStudentMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mappings', to='accounts.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_mappings', to='accounts.student')),
            ],
        ),
        migrations.AddField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', through='accounts.ParentStudentMapping', to='accounts.student'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role_type'], name='accounts_us_role_ty_b89c67_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['branch', 'role_type'], name='accounts_us_branch__a5d527_idx'),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['branch', 'level'], name='accounts_fa_branch__ab889a_idx'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('faculty_code', 'branch'), name='unique_active_faculty_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='facultyrolemapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('faculty', 'role', 'branch', 'subject', 'class_assigned', 'section'), name='unique_active_faculty_role_mapping'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('role', 'permission_key'), name='unique_active_role_permission'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['branch', 'class_assigned', 'section'], name='stu_branch_cls_sec_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('admission_number', 'branch'), name='unique_active_admission_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='parentstudentmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('parent', 'student'), name='unique_active_parent_student'),
        ),
    ]
