# Generated by Django 5.2.11 on 2026-03-03 04:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrregularityType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100)),
                ('applicable_role', models.CharField(choices=[('SECTION_INCHARGE', 'Section Incharge'), ('SUBJECT_TEACHER', 'Subject Teacher')], max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_active_irregularity_type')],
            },
        ),
        migrations.CreateModel(
            name='StudentIrregularity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('month', models.PositiveSmallIntegerField(help_text='Month number (1-12).')),
                ('date', models.DateField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='irregularities', to='core.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.branch')),
                ('irregularity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='irregularities.irregularitytype')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='irregularities', to='core.quarter')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_irregularities', to='accounts.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irregularities', to='accounts.student')),
                ('subject', models.ForeignKey(blank=True, help_text='Subject (only for SUBJECT_TEACHER irregularities).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irregularities', to='academics.subject')),
            ],
            options={
                'verbose_name_plural': 'student irregularities',
                'indexes': [models.Index(condition=models.Q(('is_deleted', False)), fields=['student', 'date'], name='irreg_stu_date_idx'), models.Index(condition=models.Q(('is_deleted', False)), fields=['branch', 'quarter', 'month'], name='irreg_branch_qtr_mon_idx')],
            },
        ),
    ]
