# Generated by Django 5.2.11 on 2026-03-03 04:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within assessment type.')),
            ],
            options={
                'ordering': ['assessment_type', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSubArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_areas', to='assessments.assessmentarea')),
            ],
            options={
                'ordering': ['area', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('description', models.TextField()),
                ('max_score', models.PositiveSmallIntegerField(default=5, help_text='Maximum score for this criteria.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('sub_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='assessments.assessmentsubarea')),
            ],
            options={
                'verbose_name_plural': 'assessment criteria',
                'ordering': ['sub_area', 'order'],
            },
        ),
        migrations.AddField(
            model_name='assessmentarea',
            name='assessment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='assessments.assessmenttype'),
        ),
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved')], default='DRAFT', max_length=10)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_assessments', to='core.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assessments', to=settings.AUTH_USER_MODEL)),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_assessments', to='assessments.assessmenttype')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.branch')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_assessments', to='core.quarter')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='accounts.student')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_assessments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssessmentScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('score', models.PositiveSmallIntegerField(help_text='Numeric score (0 to criteria.max_score).')),
                ('remarks', models.TextField(blank=True, default='')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='assessments.assessmentcriteria')),
                ('student_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assessments.studentassessment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assessmentsubarea',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('area', 'name'), name='unique_active_assessment_sub_area'),
        ),
        migrations.AddConstraint(
            model_name='assessmentarea',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('assessment_type', 'name'), name='unique_active_assessment_area'),
        ),
        migrations.AddIndex(
            model_name='studentassessment',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['student', 'quarter'], name='assmt_stu_qtr_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassessment',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['branch', 'academic_year', 'quarter'], name='assmt_branch_yr_qtr_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentassessment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('student', 'quarter', 'assessment_type'), name='unique_student_quarter_assessment'),
        ),
        migrations.AddIndex(
            model_name='studentassessmentscore',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['student_assessment', 'criteria'], name='score_assmt_crit_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentassessmentscore',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('student_assessment', 'criteria'), name='unique_active_assessment_score'),
        ),
    ]
