# Generated by Django 5.2.11 on 2026-03-03 04:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlanTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('tools_required', models.TextField(blank=True, default='', help_text='Tools/materials required for this subject.')),
                ('learning_objectives', models.TextField(blank=True, default='')),
                ('assessment_method', models.TextField(blank=True, default='')),
                ('resources', models.TextField(blank=True, default='')),
                ('homework_pattern', models.TextField(blank=True, default='')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_templates', to='core.academicyear')),
                ('created_by', models.ForeignKey(help_text='HOD who created this template.', on_delete=django.db.models.deletion.PROTECT, related_name='created_templates', to='accounts.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_templates', to='academics.subject')),
            ],
            options={
                'ordering': ['-academic_year__start_date', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='DailyLessonPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('date', models.DateField()),
                ('topic_covered', models.TextField()),
                ('homework_given', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved')], default='DRAFT', max_length=10)),
                ('approved_by', models.ForeignKey(blank=True, help_text='HOD who approved this plan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lesson_plans', to='accounts.faculty')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.branch')),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='academics.class')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_lesson_plans', to='accounts.faculty')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_plans', to='academics.section')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_plans', to='lesson_plans.lessonplantemplate')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(condition=models.Q(('is_deleted', False)), fields=['faculty', 'date'], name='dlp_faculty_date_idx'), models.Index(condition=models.Q(('is_deleted', False)), fields=['branch', 'class_assigned', 'date'], name='dlp_branch_cls_date_idx')],
            },
        ),
    ]
