# Generated by Django 5.2.11 on 2026-03-03 04:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'activity categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=300)),
                ('activity_type', models.CharField(choices=[('INTER_BRANCH', 'Inter-Branch'), ('INTER_HOUSE', 'Inter-House'), ('INTER_SCHOOL', 'Inter-School'), ('CLUB', 'Club Activity')], max_length=15)),
                ('branch_scope', models.CharField(blank=True, default='', help_text='Which branches are involved.', max_length=200)),
                ('date', models.DateField()),
                ('organized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_activities', to='accounts.faculty')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='activities.activitycategory')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('YOGA_SPORTS', 'Yoga & Sports'), ('ALL_CLUB', 'All Club (Literary, Science, etc.)')], max_length=15)),
                ('branch', models.ForeignKey(blank=True, help_text='NULL if club is global (inter-branch).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='core.branch')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('event_type', models.CharField(choices=[('ANNUAL_FUNCTION', 'Annual Function'), ('CELEBRATION', 'Celebration'), ('COMPETITION', 'Competition'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('scope', models.CharField(choices=[('BRANCH', 'Branch'), ('INTER_BRANCH', 'Inter-Branch')], default='BRANCH', max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, help_text='NULL for inter-branch events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.branch')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentClubMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mappings', to='activities.club')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_mappings', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('position', models.CharField(choices=[('WINNER', 'Winner'), ('RUNNER_UP', 'Runner Up'), ('PARTICIPANT', 'Participant')], default='PARTICIPANT', max_length=15)),
                ('remarks', models.TextField(blank=True, default='')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='activities.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_participations', to='accounts.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('student', 'activity'), name='unique_active_student_activity')],
            },
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name', 'category'), name='unique_active_club'),
        ),
        migrations.AddConstraint(
            model_name='studentclubmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('student', 'club'), name='unique_active_student_club'),
        ),
    ]
