# Generated by Django 5.2.11 on 2026-03-03 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultysubjectmapping',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_mappings', to='accounts.faculty'),
        ),
        migrations.AddField(
            model_name='house',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.branch'),
        ),
        migrations.AddField(
            model_name='section',
            name='class_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.class'),
        ),
        migrations.AddField(
            model_name='facultysubjectmapping',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_subject_mappings', to='academics.section'),
        ),
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.branch'),
        ),
        migrations.AddField(
            model_name='facultysubjectmapping',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_mappings', to='academics.subject'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['branch'], name='academics_c_branch__129771_idx'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('branch', 'name'), name='unique_active_class_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='house',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('branch', 'name'), name='unique_active_house_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('class_ref', 'name'), name='unique_active_section_per_class'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['branch'], name='academics_s_branch__819fdd_idx'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('branch', 'name'), name='unique_active_subject_per_branch'),
        ),
        migrations.AddIndex(
            model_name='facultysubjectmapping',
            index=models.Index(fields=['class_assigned', 'section'], name='academics_f_class_a_814b74_idx'),
        ),
        migrations.AddConstraint(
            model_name='facultysubjectmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('faculty', 'subject', 'class_assigned', 'section'), name='unique_active_faculty_subject_class_section'),
        ),
    ]
