# Generated by Django 5.2.11 on 2026-03-03 04:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order in academic calendar.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='core.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.branch')),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academics.class')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='exams.examtype')),
            ],
        ),
        migrations.CreateModel(
            name='ExamMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='accounts.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_marks', to='academics.subject')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('is_deleted', False)), fields=['student', 'exam'], name='mark_stu_exam_idx'), models.Index(condition=models.Q(('is_deleted', False)), fields=['exam', 'subject'], name='mark_exam_subj_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('student', 'exam', 'subject'), name='unique_student_exam_subject_mark')],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['branch', 'academic_year'], name='exam_branch_year_idx'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('exam_type', 'academic_year', 'branch', 'class_assigned'), name='unique_active_exam_per_class'),
        ),
    ]
